### ISSUE TITLE
How can I remove this?

### ISSUE THREAD

**Issue by Lewiscowles1986** [elgatosf/streamdeck-numberdisplay#1]
So I followed the instructions, but this does not display on my StreamDeck and I don't seem to be able to remove it either. 

Edit: [See Manually removing plugin link](https://help.elgato.com/hc/en-us/articles/11434818801293-Elgato-Stream-Deck-How-to-Install-and-Uninstall-Stream-Deck-Plugins-#h_01GM73PP447HK3D877V2P8B8VF:~:text=Uninstall%20to%20proceed.-,Manually%20Removing%20a%20Plugin,-If%20you%20cannot)

**Comment by Lewiscowles1986** [comment]
Is this actually solved? Sorry there is no link to a commit or any kind of feedback, just DevRel closed.

**Comment by ChekTek** [comment]
Hi @Lewiscowles1986 

My apologies! I misread the original post. This plugin did not have a category & category icon available, so it would have shown up under "Custom" in the actions list. 

I've now given it a category and category icon, please let me know if you are still not seeing it in the actions list and provide the version of Stream Deck you are using, and I'll explore the issue further.
